name       : openfx-io
version    : 2.3.0
release    : 2
source     :
    - git|https://github.com/MrKepzie/openfx-io.git : Natron-2.3.0
license    : GPL-2.0
component  : multimedia.graphics
summary    : A set of OpenFX readers and writers plugins
description: |
    A set of OpenFX readers and writers plugins
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libcdr-0.1)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(librevenge-0.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(Magick++)
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - pkgconfig(poppler)
    - openimageio-devel
    - seexpr-devel
build      : |
    %make CONFIG=release IM=7
install    : |
    %make_install \
        PLUGINPATH=/usr/share/OFX/Plugins \
        CONFIG=release \
        IM=7
